name: Go
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.1

      - uses: actions/checkout@v3

      - name: lint
        run: go run github.com/ysmood/golangci-lint@latest
        if: matrix.os == 'ubuntu-latest'

      - name: test
        run: go test ./...
